name: Release Drafter
on:
  push:
    # 해당 브랜치에 push될 때 action 이 실행된다.
    branches:
      - master
      
jobs:
  update_release_draft:
    runs-on: ubuntu-latest  #ubuntu OS에서 실행됨
    steps:
      - uses: release-drafter/release-drafter@v5  #Release-drafter의 v5를 이용
        # (Optional)
        # workflow 에서 여러 구성이 필요할 때 config-name 에 오버라이드 해줍니다.
        # 반드시 .github/ 에 위치해야합니다.
        with:
          config-name: workflows/release-drafter-config.yml #.github 기준의 경로
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
